In [2]:
import pandas as pd

In [3]:
df= pd.read_csv(r'Downloads/dataset and all/training_set_features.csv')

In [4]:
df.head()

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,NaN
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,"<= $75,000, Above Poverty",Married,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb

In [4]:
df

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,NaN
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,"<= $75,000, Above Poverty",Married,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26702,26702,2.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,"<= $75,000, Above Poverty",Not Married,Own,Not in Labor Force,qufhixun,Non-MSA,0.0,0.0,NaN,NaN
26703,26703,1.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Not Married,Rent,Employed,lzgpxyit,"MSA, Principle City",1.0,0.0,fcxhlnwr,cmhcxjea
26704,26704,2.0,2.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,NaN,Not Married,Own,NaN,lzgpxyit,"MSA, Not Principle City",0.0,0.0,NaN,NaN
26705,26705,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,...,"<= $75,000, Above Poverty",Married,Rent,Employed,lrircsnp,Non-MSA,1.0,0.0,fcxhlnwr,haliazsg
26706,26706,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Married,Own,Not in Labor Force,mlyzmhmf,"MSA, Principle City",1.0,0.0,NaN,NaN

In [5]:
df2= pd.read_csv(r'Downloads/dataset and all/training_set_labels.csv')

In [6]:
df2

       respondent_id  xyz_vaccine  seasonal_vaccine
0                  0            0                 0
1                  1            0                 1
2                  2            0                 0
3                  3            0                 1
4                  4            0                 0
...              ...          ...               ...
26702          26702            0                 0
26703          26703            0                 0
26704          26704            0                 1
26705          26705            0                 0
26706          26706            0                 0

[26707 rows x 3 columns]

In [12]:
df.drop(['employment_industry','employment_occupation','hhs_geo_region','rent_or_own'], axis= 1, inplace= True)

KeyError: "['employment_industry', 'employment_occupation', 'hhs_geo_region'] not found in axis"

In [11]:
df

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,education,race,sex,income_poverty,marital_status,rent_or_own,employment_status,census_msa,household_adults,household_children
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,< 12 Years,White,Female,Below Poverty,Not Married,Own,Not in Labor Force,Non-MSA,0.0,0.0
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,12 Years,White,Male,Below Poverty,Not Married,Rent,Employed,"MSA, Not Principle City",0.0,0.0
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,College Graduate,White,Male,"<= $75,000, Above Poverty",Not Married,Own,Employed,"MSA, Not Principle City",2.0,0.0
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,12 Years,White,Female,Below Poverty,Not Married,Rent,Not in Labor Force,"MSA, Principle City",0.0,0.0
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,Some College,White,Female,"<= $75,000, Above Poverty",Married,Own,Employed,"MSA, Not Principle City",1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26702,26702,2.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,Some College,White,Female,"<= $75,000, Above Poverty",Not Married,Own,Not in Labor Force,Non-MSA,0.0,0.0
26703,26703,1.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,College Graduate,White,Male,"<= $75,000, Above Poverty",Not Married,Rent,Employed,"MSA, Principle City",1.0,0.0
26704,26704,2.0,2.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,Some College,White,Female,NaN,Not Married,Own,NaN,"MSA, Not Principle City",0.0,0.0
26705,26705,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,...,Some College,Hispanic,Female,"<= $75,000, Above Poverty",Married,Rent,Employed,Non-MSA,1.0,0.0
26706,26706,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,Some College,White,Male,"<= $75,000, Above Poverty",Married,Own,Not in Labor Force,"MSA, Principle City",1.0,0.0

In [9]:
df.employment_status.value_counts()

employment_status
Employed              13560
Not in Labor Force    10231
Unemployed             1453
Name: count, dtype: int64

In [13]:
df

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,education,race,sex,income_poverty,marital_status,rent_or_own,employment_status,census_msa,household_adults,household_children
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,< 12 Years,White,Female,Below Poverty,Not Married,Own,Not in Labor Force,Non-MSA,0.0,0.0
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,12 Years,White,Male,Below Poverty,Not Married,Rent,Employed,"MSA, Not Principle City",0.0,0.0
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,College Graduate,White,Male,"<= $75,000, Above Poverty",Not Married,Own,Employed,"MSA, Not Principle City",2.0,0.0
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,12 Years,White,Female,Below Poverty,Not Married,Rent,Not in Labor Force,"MSA, Principle City",0.0,0.0
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,Some College,White,Female,"<= $75,000, Above Poverty",Married,Own,Employed,"MSA, Not Principle City",1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26702,26702,2.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,Some College,White,Female,"<= $75,000, Above Poverty",Not Married,Own,Not in Labor Force,Non-MSA,0.0,0.0
26703,26703,1.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,College Graduate,White,Male,"<= $75,000, Above Poverty",Not Married,Rent,Employed,"MSA, Principle City",1.0,0.0
26704,26704,2.0,2.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,Some College,White,Female,NaN,Not Married,Own,NaN,"MSA, Not Principle City",0.0,0.0
26705,26705,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,...,Some College,Hispanic,Female,"<= $75,000, Above Poverty",Married,Rent,Employed,Non-MSA,1.0,0.0
26706,26706,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,Some College,White,Male,"<= $75,000, Above Poverty",Married,Own,Not in Labor Force,"MSA, Principle City",1.0,0.0

In [14]:
df.drop(['rent_or_own'], axis= 1, inplace= True)

In [15]:
df

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,age_group,education,race,sex,income_poverty,marital_status,employment_status,census_msa,household_adults,household_children
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,55 - 64 Years,< 12 Years,White,Female,Below Poverty,Not Married,Not in Labor Force,Non-MSA,0.0,0.0
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,35 - 44 Years,12 Years,White,Male,Below Poverty,Not Married,Employed,"MSA, Not Principle City",0.0,0.0
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,18 - 34 Years,College Graduate,White,Male,"<= $75,000, Above Poverty",Not Married,Employed,"MSA, Not Principle City",2.0,0.0
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,65+ Years,12 Years,White,Female,Below Poverty,Not Married,Not in Labor Force,"MSA, Principle City",0.0,0.0
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,45 - 54 Years,Some College,White,Female,"<= $75,000, Above Poverty",Married,Employed,"MSA, Not Principle City",1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26702,26702,2.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,65+ Years,Some College,White,Female,"<= $75,000, Above Poverty",Not Married,Not in Labor Force,Non-MSA,0.0,0.0
26703,26703,1.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,18 - 34 Years,College Graduate,White,Male,"<= $75,000, Above Poverty",Not Married,Employed,"MSA, Principle City",1.0,0.0
26704,26704,2.0,2.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,55 - 64 Years,Some College,White,Female,NaN,Not Married,NaN,"MSA, Not Principle City",0.0,0.0
26705,26705,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,...,18 - 34 Years,Some College,Hispanic,Female,"<= $75,000, Above Poverty",Married,Employed,Non-MSA,1.0,0.0
26706,26706,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,65+ Years,Some College,White,Male,"<= $75,000, Above Poverty",Married,Not in Labor Force,"MSA, Principle City",1.0,0.0

In [16]:
df.columns[df.isna().any()]

Index(['xyz_concern', 'xyz_knowledge', 'behavioral_antiviral_meds',
       'behavioral_avoidance', 'behavioral_face_mask', 'behavioral_wash_hands',
       'behavioral_large_gatherings', 'behavioral_outside_home',
       'behavioral_touch_face', 'doctor_recc_xyz', 'doctor_recc_seasonal',
       'chronic_med_condition', 'child_under_6_months', 'health_worker',
       'health_insurance', 'opinion_xyz_vacc_effective', 'opinion_xyz_risk',
       'opinion_xyz_sick_from_vacc', 'opinion_seas_vacc_effective',
       'opinion_seas_risk', 'opinion_seas_sick_from_vacc', 'education',
       'income_poverty', 'marital_status', 'employment_status',
       'household_adults', 'household_children'],
      dtype='object')

In [17]:
df.xyz_concern

0        1.0
1        3.0
2        1.0
3        1.0
4        2.0
        ...
26702    2.0
26703    1.0
26704    2.0
26705    1.0
26706    0.0
Name: xyz_concern, Length: 26707, dtype: float64

In [18]:
df.xyz_concern.value_counts()

xyz_concern
2.0    10575
1.0     8153
3.0     4591
0.0     3296
Name: count, dtype: int64

In [20]:
df.xyz_concern.isna().sum()

92

In [21]:
df.drop(['marital_status'], axis= 1, inplace= True)

In [23]:
df.xyz_concern.mean()

1.6184858162690212

In [24]:
df.xyz_concern= df.xyz_concern.fillna(2.0)

In [25]:
df.xyz_concern.value_counts()

xyz_concern
2.0    10667
1.0     8153
3.0     4591
0.0     3296
Name: count, dtype: int64

In [26]:
df.xyz_knowledge.isna().sum()

116

In [32]:
df.xyz_knowledge.mode()

0    1.0
Name: xyz_knowledge, dtype: float64

In [35]:
df.xyz_knowledge= df.xyz_knowledge.fillna(1.0)

In [51]:
df.isna().sum()

respondent_id                     0
xyz_concern                       0
xyz_knowledge                     0
behavioral_antiviral_meds        71
behavioral_avoidance            208
behavioral_face_mask             19
behavioral_wash_hands            42
behavioral_large_gatherings      87
behavioral_outside_home          82
behavioral_touch_face           128
doctor_recc_xyz                2160
doctor_recc_seasonal           2160
chronic_med_condition           971
child_under_6_months            820
health_worker                   804
opinion_xyz_vacc_effective      391
opinion_xyz_risk                388
opinion_xyz_sick_from_vacc      395
opinion_seas_vacc_effective     462
opinion_seas_risk               514
opinion_seas_sick_from_vacc     537
age_group                         0
education                         0
race                              0
sex                               0
income_poverty                    0
employment_status              1463
census_msa                        0
household_adults                249
household_children              249
dtype: int64

In [37]:
df.health_insurance.value_counts()

health_insurance
1.0    12697
0.0     1736
Name: count, dtype: int64

In [38]:
df.drop(['health_insurance'], axis= 1, inplace= True)

In [49]:
df.income_poverty.value_counts()

income_poverty
<= $75,000, Above Poverty    12777
> $75,000                     6810
<= $75,000                    4423
Below Poverty                 2697
Name: count, dtype: int64

In [41]:
df.income_poverty= df.income_poverty.fillna('<= $75,000')

In [50]:
df.income_poverty.value_counts()

income_poverty
<= $75,000, Above Poverty    12777
> $75,000                     6810
<= $75,000                    4423
Below Poverty                 2697
Name: count, dtype: int64

In [45]:
df.education.value_counts()

education
College Graduate    11504
Some College         7043
12 Years             5797
< 12 Years           2363
Name: count, dtype: int64

In [55]:
df.education= df.education.fillna('College Graduate')

In [54]:
df.education.value_counts()

education
College Graduate    11504
Some College         7043
12 Years             5797
< 12 Years           2363
Name: count, dtype: int64

In [56]:
df.isna()

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,opinion_seas_sick_from_vacc,age_group,education,race,sex,income_poverty,employment_status,census_msa,household_adults,household_children
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26702,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26703,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26704,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
26705,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
26706,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [114]:
df.isna().sum()

respondent_id                  0
xyz_concern                    0
xyz_knowledge                  0
behavioral_antiviral_meds      0
behavioral_avoidance           0
behavioral_face_mask           0
behavioral_wash_hands          0
behavioral_large_gatherings    0
behavioral_outside_home        0
behavioral_touch_face          0
doctor_recc_xyz                0
doctor_recc_seasonal           0
chronic_med_condition          0
child_under_6_months           0
health_worker                  0
opinion_xyz_vacc_effective     0
opinion_xyz_risk               0
opinion_xyz_sick_from_vacc     0
opinion_seas_vacc_effective    0
opinion_seas_risk              0
opinion_seas_sick_from_vacc    0
age_group                      0
education                      0
race                           0
sex                            0
income_poverty                 0
employment_status              0
census_msa                     0
household_adults               0
household_children             0
dtype: int64

In [58]:
df.doctor_recc_xyz.mode()

0    0.0
Name: doctor_recc_xyz, dtype: float64

In [59]:
df.doctor_recc_seasonal.mode()

0    0.0
Name: doctor_recc_seasonal, dtype: float64

In [62]:
df.doctor_recc_xyz= df.doctor_recc_xyz.fillna(0.0)

In [63]:
df.doctor_recc_seasonal= df.doctor_recc_seasonal.fillna(0.0)

In [65]:
df.employment_status.mode()

0    Employed
Name: employment_status, dtype: object

In [66]:
df.employment_status= df.employment_status.fillna('Employed')

In [68]:
df.chronic_med_condition.mode()

0    0.0
Name: chronic_med_condition, dtype: float64

In [69]:
df.chronic_med_condition= df.chronic_med_condition.fillna(0.0)

In [70]:
df.child_under_6_months.mode()

0    0.0
Name: child_under_6_months, dtype: float64

In [71]:
df.child_under_6_months= df.child_under_6_months.fillna(0.0)

In [72]:
df.health_worker.mode()

0    0.0
Name: health_worker, dtype: float64

In [73]:
df.health_worker= df.health_worker.fillna(0.0)

In [74]:
df.opinion_xyz_vacc_effective.mode()

0    4.0
Name: opinion_xyz_vacc_effective, dtype: float64

In [75]:
df.opinion_xyz_vacc_effective= df.opinion_xyz_vacc_effective.fillna(4.0)

In [76]:
df.opinion_xyz_risk.mode()

0    2.0
Name: opinion_xyz_risk, dtype: float64

In [77]:
df.opinion_xyz_risk= df.opinion_xyz_risk.fillna(2.0)

In [79]:
df.opinion_xyz_sick_from_vacc.mode()

0    2.0
Name: opinion_xyz_sick_from_vacc, dtype: float64

In [80]:
df.opinion_xyz_sick_from_vacc= df.opinion_xyz_sick_from_vacc.fillna(2.0)

In [81]:
df.opinion_seas_vacc_effective.mode()

0    4.0
Name: opinion_seas_vacc_effective, dtype: float64

In [82]:
df.opinion_seas_vacc_effective= df.opinion_seas_vacc_effective.fillna(4.0)

In [84]:
df.opinion_seas_risk.mode()

0    2.0
Name: opinion_seas_risk, dtype: float64

In [87]:
df.opinion_seas_risk= df.opinion_seas_risk.fillna(2.0)

In [89]:
df.opinion_seas_sick_from_vacc.mode()

0    1.0
Name: opinion_seas_sick_from_vacc, dtype: float64

In [90]:
df.opinion_seas_sick_from_vacc= df.opinion_seas_sick_from_vacc.fillna(1.0)

In [92]:
df.household_adults.mode()

0    1.0
Name: household_adults, dtype: float64

In [93]:
df.household_adults= df.household_adults.fillna(1.0)

In [94]:
df.household_children.mode()

0    0.0
Name: household_children, dtype: float64

In [95]:
df.household_children= df.household_children.fillna(0.0)

In [97]:
df.behavioral_antiviral_meds.mode()

0    0.0
Name: behavioral_antiviral_meds, dtype: float64

In [98]:
df.behavioral_antiviral_meds= df.behavioral_antiviral_meds.fillna(0.0)

In [99]:
df.behavioral_avoidance.mode()

0    1.0
Name: behavioral_avoidance, dtype: float64

In [100]:
df.behavioral_avoidance= df.behavioral_avoidance.fillna(1.0)

In [101]:
df.behavioral_face_mask.mode()

0    0.0
Name: behavioral_face_mask, dtype: float64

In [102]:
df.behavioral_face_mask= df.behavioral_face_mask.fillna(0.0)

In [104]:
df.behavioral_touch_face.mode()

0    1.0
Name: behavioral_touch_face, dtype: float64

In [106]:
df.behavioral_touch_face= df.behavioral_touch_face.fillna(1.0)

In [107]:
df.behavioral_outside_home.mode()

0    0.0
Name: behavioral_outside_home, dtype: float64

In [108]:
df.behavioral_outside_home= df.behavioral_outside_home.fillna(0.0)

In [110]:
df.behavioral_large_gatherings.mode()

0    0.0
Name: behavioral_large_gatherings, dtype: float64

In [111]:
df.behavioral_large_gatherings= df.behavioral_large_gatherings.fillna(0.0)

In [112]:
df.behavioral_wash_hands.mode()

0    1.0
Name: behavioral_wash_hands, dtype: float64

In [113]:
df.behavioral_wash_hands= df.behavioral_wash_hands.fillna(1.0)

In [115]:
target1= df2.xyz_vaccine

In [116]:
target2= df2.seasonal_vaccine

In [118]:
df.columns

Index(['respondent_id', 'xyz_concern', 'xyz_knowledge',
       'behavioral_antiviral_meds', 'behavioral_avoidance',
       'behavioral_face_mask', 'behavioral_wash_hands',
       'behavioral_large_gatherings', 'behavioral_outside_home',
       'behavioral_touch_face', 'doctor_recc_xyz', 'doctor_recc_seasonal',
       'chronic_med_condition', 'child_under_6_months', 'health_worker',
       'opinion_xyz_vacc_effective', 'opinion_xyz_risk',
       'opinion_xyz_sick_from_vacc', 'opinion_seas_vacc_effective',
       'opinion_seas_risk', 'opinion_seas_sick_from_vacc', 'age_group',
       'education', 'race', 'sex', 'income_poverty', 'employment_status',
       'census_msa', 'household_adults', 'household_children'],
      dtype='object')

In [120]:
input1= df[['xyz_concern', 'xyz_knowledge',
       'behavioral_antiviral_meds', 'behavioral_avoidance',
       'behavioral_face_mask', 'behavioral_wash_hands',
       'behavioral_large_gatherings', 'behavioral_outside_home',
       'behavioral_touch_face', 'doctor_recc_xyz','chronic_med_condition', 'child_under_6_months', 'health_worker',
       'opinion_xyz_vacc_effective', 'opinion_xyz_risk',
       'opinion_xyz_sick_from_vacc', 'age_group',
       'education', 'race', 'sex', 'income_poverty', 'employment_status',
       'census_msa', 'household_adults', 'household_children']]

In [121]:
input1

,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_xyz,...,opinion_xyz_sick_from_vacc,age_group,education,race,sex,income_poverty,employment_status,census_msa,household_adults,household_children
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,2.0,55 - 64 Years,< 12 Years,White,Female,Below Poverty,Not in Labor Force,Non-MSA,0.0,0.0
1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,...,4.0,35 - 44 Years,12 Years,White,Male,Below Poverty,Employed,"MSA, Not Principle City",0.0,0.0
2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,18 - 34 Years,College Graduate,White,Male,"<= $75,000, Above Poverty",Employed,"MSA, Not Principle City",2.0,0.0
3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,5.0,65+ Years,12 Years,White,Female,Below Poverty,Not in Labor Force,"MSA, Principle City",0.0,0.0
4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,...,2.0,45 - 54 Years,Some College,White,Female,"<= $75,000, Above Poverty",Employed,"MSA, Not Principle City",1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26702,2.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,65+ Years,Some College,White,Female,"<= $75,000, Above Poverty",Not in Labor Force,Non-MSA,0.0,0.0
26703,1.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,2.0,18 - 34 Years,College Graduate,White,Male,"<= $75,000, Above Poverty",Employed,"MSA, Principle City",1.0,0.0
26704,2.0,2.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,...,2.0,55 - 64 Years,Some College,White,Female,"<= $75,000",Employed,"MSA, Not Principle City",0.0,0.0
26705,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,2.0,18 - 34 Years,Some College,Hispanic,Female,"<= $75,000, Above Poverty",Employed,Non-MSA,1.0,0.0
26706,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,65+ Years,Some College,White,Male,"<= $75,000, Above Poverty",Not in Labor Force,"MSA, Principle City",1.0,0.0

In [151]:
dummies1= pd.get_dummies(df.sex,dtype= float)

In [135]:
dummies1.head()

   Female  Male
0     1.0   0.0
1     0.0   1.0
2     0.0   1.0
3     1.0   0.0
4     1.0   0.0

In [150]:
dummies2= pd.get_dummies(df.race,dtype= float)

In [138]:
dummies2.head()

   Black  Hispanic  Other or Multiple  White
0    0.0       0.0                0.0    1.0
1    0.0       0.0                0.0    1.0
2    0.0       0.0                0.0    1.0
3    0.0       0.0                0.0    1.0
4    0.0       0.0                0.0    1.0

In [145]:
dummies3= pd.get_dummies(df.employment_status,dtype= float)

In [146]:
dummies4= pd.get_dummies(df.census_msa,dtype= float)

In [147]:
dummies5= pd.get_dummies(df.income_poverty,dtype= float)

In [148]:
dummies6= pd.get_dummies(df.age_group,dtype= float)

In [149]:
dummies7= pd.get_dummies(df.education,dtype= float)

In [152]:
input1= pd.concat([input1,dummies1,dummies2,dummies3,dummies4,dummies5,dummies6,dummies7], axis= 'columns')

In [153]:
input1.head()

,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_xyz,...,Below Poverty,18 - 34 Years,35 - 44 Years,45 - 54 Years,55 - 64 Years,65+ Years,12 Years,< 12 Years,College Graduate,Some College
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [155]:
input1.columns

Index(['xyz_concern', 'xyz_knowledge', 'behavioral_antiviral_meds',
       'behavioral_avoidance', 'behavioral_face_mask', 'behavioral_wash_hands',
       'behavioral_large_gatherings', 'behavioral_outside_home',
       'behavioral_touch_face', 'doctor_recc_xyz', 'chronic_med_condition',
       'child_under_6_months', 'health_worker', 'opinion_xyz_vacc_effective',
       'opinion_xyz_risk', 'opinion_xyz_sick_from_vacc', 'age_group',
       'education', 'race', 'sex', 'income_poverty', 'employment_status',
       'census_msa', 'household_adults', 'household_children', 'Female',
       'Male', 'Black', 'Hispanic', 'Other or Multiple', 'White', 'Employed',
       'Not in Labor Force', 'Unemployed', 'MSA, Not Principle  City',
       'MSA, Principle City', 'Non-MSA', '<= $75,000',
       '<= $75,000, Above Poverty', '> $75,000', 'Below Poverty',
       '18 - 34 Years', '35 - 44 Years', '45 - 54 Years', '55 - 64 Years',
       '65+ Years', '12 Years', '< 12 Years', 'College Graduate',
       'Some College'],
      dtype='object')

In [157]:
input1.drop(['age_group',
       'education', 'race', 'sex', 'income_poverty', 'employment_status',
       'census_msa'], axis= 1, inplace= True)

In [158]:
input1.columns

Index(['xyz_concern', 'xyz_knowledge', 'behavioral_antiviral_meds',
       'behavioral_avoidance', 'behavioral_face_mask', 'behavioral_wash_hands',
       'behavioral_large_gatherings', 'behavioral_outside_home',
       'behavioral_touch_face', 'doctor_recc_xyz', 'chronic_med_condition',
       'child_under_6_months', 'health_worker', 'opinion_xyz_vacc_effective',
       'opinion_xyz_risk', 'opinion_xyz_sick_from_vacc', 'household_adults',
       'household_children', 'Female', 'Male', 'Black', 'Hispanic',
       'Other or Multiple', 'White', 'Employed', 'Not in Labor Force',
       'Unemployed', 'MSA, Not Principle  City', 'MSA, Principle City',
       'Non-MSA', '<= $75,000', '<= $75,000, Above Poverty', '> $75,000',
       'Below Poverty', '18 - 34 Years', '35 - 44 Years', '45 - 54 Years',
       '55 - 64 Years', '65+ Years', '12 Years', '< 12 Years',
       'College Graduate', 'Some College'],
      dtype='object')

In [159]:
input1.head()

,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_xyz,...,Below Poverty,18 - 34 Years,35 - 44 Years,45 - 54 Years,55 - 64 Years,65+ Years,12 Years,< 12 Years,College Graduate,Some College
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [164]:
input2= df[['behavioral_antiviral_meds', 'behavioral_avoidance',
       'behavioral_face_mask', 'behavioral_wash_hands',
       'behavioral_large_gatherings', 'behavioral_outside_home',
       'behavioral_touch_face', 'doctor_recc_seasonal', 'chronic_med_condition', 'child_under_6_months', 'health_worker', 'opinion_seas_vacc_effective',
       'opinion_seas_risk', 'opinion_seas_sick_from_vacc', 'age_group',
       'education', 'race', 'sex', 'income_poverty', 'employment_status',
       'census_msa', 'household_adults', 'household_children']]

In [165]:
input2= pd.concat([input2,dummies1,dummies2,dummies3,dummies4,dummies5,dummies6,dummies7],axis=1)

In [166]:
input2.drop(['age_group',
       'education', 'race', 'sex', 'income_poverty', 'employment_status',
       'census_msa'],axis=1,inplace=True)

In [167]:
input2.columns

Index(['behavioral_antiviral_meds', 'behavioral_avoidance',
       'behavioral_face_mask', 'behavioral_wash_hands',
       'behavioral_large_gatherings', 'behavioral_outside_home',
       'behavioral_touch_face', 'doctor_recc_seasonal',
       'chronic_med_condition', 'child_under_6_months', 'health_worker',
       'opinion_seas_vacc_effective', 'opinion_seas_risk',
       'opinion_seas_sick_from_vacc', 'household_adults', 'household_children',
       'Female', 'Male', 'Black', 'Hispanic', 'Other or Multiple', 'White',
       'Employed', 'Not in Labor Force', 'Unemployed',
       'MSA, Not Principle  City', 'MSA, Principle City', 'Non-MSA',
       '<= $75,000', '<= $75,000, Above Poverty', '> $75,000', 'Below Poverty',
       '18 - 34 Years', '35 - 44 Years', '45 - 54 Years', '55 - 64 Years',
       '65+ Years', '12 Years', '< 12 Years', 'College Graduate',
       'Some College'],
      dtype='object')

In [230]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(input1,target1,test_size=0.28)

In [273]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train,y_train)

MultinomialNB()

In [231]:
model.score(X_test, y_test)

0.8147900508157261

In [232]:
X_test[0:10]

,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_xyz,...,Below Poverty,18 - 34 Years,35 - 44 Years,45 - 54 Years,55 - 64 Years,65+ Years,12 Years,< 12 Years,College Graduate,Some College
7296,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
22149,2.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9872,3.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
775,3.0,2.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
23013,2.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
16725,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
20620,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
12752,0.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
20557,2.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
11370,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [233]:
y_test[0:10]

7296     0
22149    0
9872     0
775      1
23013    0
16725    0
20620    0
12752    0
20557    0
11370    0
Name: xyz_vaccine, dtype: int64

In [234]:
model.predict(X_test[0:10])

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0], dtype=int64)

In [290]:
model.predict_proba(X_test[:10])[:,1]

array([0.28857922, 0.15938093, 0.17144101, 0.57514489, 0.19571088,
       0.18176607, 0.13293374, 0.1128171 , 0.13705946, 0.05754341])

In [236]:
test_csv= pd.read_csv(r'Downloads/dataset and all/test_set_features.csv')

In [237]:
test_csv.head()

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
0,26707,2.0,2.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,"> $75,000",Not Married,Rent,Employed,mlyzmhmf,"MSA, Not Principle City",1.0,0.0,atmlpfrs,hfxkjkmi
1,26708,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,Non-MSA,3.0,0.0,atmlpfrs,xqwwgdyp
2,26709,2.0,2.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,...,"> $75,000",Married,Own,Employed,lrircsnp,Non-MSA,1.0,0.0,nduyfdeo,pvmttkik
3,26710,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Married,Own,Not in Labor Force,lrircsnp,"MSA, Not Principle City",1.0,0.0,NaN,NaN
4,26711,3.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,lzgpxyit,Non-MSA,0.0,1.0,fcxhlnwr,mxkfnird

In [247]:
test_csv.isna().sum()

respondent_id                  0
xyz_concern                    1
xyz_knowledge                  1
behavioral_antiviral_meds      1
behavioral_avoidance           1
behavioral_face_mask           1
behavioral_wash_hands          1
behavioral_large_gatherings    1
behavioral_outside_home        1
behavioral_touch_face          1
doctor_recc_xyz                1
doctor_recc_seasonal           1
chronic_med_condition          1
child_under_6_months           1
health_worker                  1
opinion_xyz_vacc_effective     1
opinion_xyz_risk               1
opinion_xyz_sick_from_vacc     1
opinion_seas_vacc_effective    1
opinion_seas_risk              1
opinion_seas_sick_from_vacc    1
age_group                      0
education                      1
race                           0
sex                            0
income_poverty                 1
employment_status              1
census_msa                     0
household_adults               1
household_children             1
dtype: int64

In [239]:
test_csv.drop(['rent_or_own','employment_industry','hhs_geo_region','marital_status','health_insurance'],axis=1,inplace=True)

In [254]:
test_csv.xyz_concern= test_csv.xyz_concern.fillna(2.0)

In [255]:
test_csv.behavioral_wash_hands= test_csv.behavioral_wash_hands.fillna(1.0)

In [256]:
test_csv.behavioral_large_gatherings= test_csv.behavioral_large_gatherings.fillna(0.0)
test_csv.behavioral_outside_home= test_csv.behavioral_outside_home.fillna(0.0)
test_csv.behavioral_touch_face= test_csv.behavioral_touch_face.fillna(1.0)
test_csv.behavioral_face_mask= test_csv.behavioral_face_mask.fillna(0.0)
test_csv.behavioral_avoidance= test_csv.behavioral_avoidance.fillna(1.0)
test_csv.behavioral_antiviral_meds= test_csv.behavioral_antiviral_meds.fillna(0.0)
test_csv.household_children= test_csv.household_children.fillna(0.0)
test_csv.household_adults= test_csv.household_adults.fillna(1.0)
test_csv.opinion_seas_sick_from_vacc= test_csv.opinion_seas_sick_from_vacc.fillna(1.0)
test_csv.opinion_seas_risk= test_csv.opinion_seas_risk.fillna(2.0)
test_csv.opinion_seas_vacc_effective= test_csv.opinion_seas_vacc_effective.fillna(4.0)
test_csv.opinion_xyz_sick_from_vacc= test_csv.opinion_xyz_sick_from_vacc.fillna(2.0)
test_csv.opinion_xyz_risk= test_csv.opinion_xyz_risk.fillna(2.0)
test_csv.opinion_xyz_vacc_effective= test_csv.opinion_xyz_vacc_effective.fillna(4.0)
test_csv.health_worker= test_csv.health_worker.fillna(0.0)
test_csv.child_under_6_months= test_csv.child_under_6_months.fillna(0.0)
test_csv.chronic_med_condition= test_csv.chronic_med_condition.fillna(0.0)
test_csv.employment_status= test_csv.employment_status.fillna('Employed')
test_csv.doctor_recc_seasonal= test_csv.doctor_recc_seasonal.fillna(0.0)
test_csv.doctor_recc_xyz= test_csv.doctor_recc_xyz.fillna(0.0)
test_csv.education= test_csv.education.fillna('College Graduate')
test_csv.income_poverty= test_csv.income_poverty.fillna('<= $75,000')
test_csv.xyz_knowledge= test_csv.xyz_knowledge.fillna(1.0)

In [244]:
test_csv.drop(['employment_occupation'], axis= 1, inplace= True)

ValueError: Index data must be 1-dimensional

In [257]:
test_csv.isna().sum()

respondent_id                  0
xyz_concern                    0
xyz_knowledge                  0
behavioral_antiviral_meds      0
behavioral_avoidance           0
behavioral_face_mask           0
behavioral_wash_hands          0
behavioral_large_gatherings    0
behavioral_outside_home        0
behavioral_touch_face          0
doctor_recc_xyz                0
doctor_recc_seasonal           0
chronic_med_condition          0
child_under_6_months           0
health_worker                  0
opinion_xyz_vacc_effective     0
opinion_xyz_risk               0
opinion_xyz_sick_from_vacc     0
opinion_seas_vacc_effective    0
opinion_seas_risk              0
opinion_seas_sick_from_vacc    0
age_group                      0
education                      0
race                           0
sex                            0
income_poverty                 0
employment_status              0
census_msa                     0
household_adults               0
household_children             0
dtype: int64

In [258]:
dummie1= pd.get_dummies(test_csv.sex,dtype= float)
dummie2= pd.get_dummies(test_csv.race,dtype= float)
dummie3= pd.get_dummies(test_csv.employment_status,dtype= float)
dummie4= pd.get_dummies(test_csv.census_msa,dtype= float)
dummie5= pd.get_dummies(test_csv.income_poverty,dtype= float)
dummie6= pd.get_dummies(test_csv.age_group,dtype= float)
dummie7= pd.get_dummies(test_csv.education,dtype= float)

In [260]:
X_test_xyz= test_csv[['xyz_concern', 'xyz_knowledge',
       'behavioral_antiviral_meds', 'behavioral_avoidance',
       'behavioral_face_mask', 'behavioral_wash_hands',
       'behavioral_large_gatherings', 'behavioral_outside_home',
       'behavioral_touch_face', 'doctor_recc_xyz','chronic_med_condition', 'child_under_6_months', 'health_worker',
       'opinion_xyz_vacc_effective', 'opinion_xyz_risk',
       'opinion_xyz_sick_from_vacc', 'age_group',
       'education', 'race', 'sex', 'income_poverty', 'employment_status',
       'census_msa', 'household_adults', 'household_children']]

In [261]:
X_test_xyz= pd.concat([X_test_xyz,dummie1,dummie2,dummie3,dummie4,dummie5,dummie6,dummie7],axis=1)

In [263]:
X_test_seasonal= test_csv[['behavioral_antiviral_meds', 'behavioral_avoidance',
       'behavioral_face_mask', 'behavioral_wash_hands',
       'behavioral_large_gatherings', 'behavioral_outside_home',
       'behavioral_touch_face', 'doctor_recc_seasonal', 'chronic_med_condition', 'child_under_6_months', 'health_worker', 'opinion_seas_vacc_effective',
       'opinion_seas_risk', 'opinion_seas_sick_from_vacc', 'age_group',
       'education', 'race', 'sex', 'income_poverty', 'employment_status',
       'census_msa', 'household_adults', 'household_children']]

In [264]:
X_test_seasonal= pd.concat([X_test_seasonal,dummie1,dummie2,dummie3,dummie4,dummie5,dummie6,dummie7],axis=1)

In [265]:
X_test_seasonal.drop(['age_group',
       'education', 'race', 'sex', 'income_poverty', 'employment_status',
       'census_msa'],axis=1,inplace=True)

In [266]:
X_test_xyz.drop(['age_group',
       'education', 'race', 'sex', 'income_poverty', 'employment_status',
       'census_msa'],axis=1,inplace=True)

In [292]:
xyz_predicted=model.predict_proba(X_test_xyz)[:,1]

In [271]:
xyz_label_predicted=model.predict(X_test_xyz)

In [278]:
from sklearn.model_selection import train_test_split
X_train2, X_test2, y_train2, y_test2 = train_test_split(input2,target2,test_size=0.20)

In [274]:

model2 = MultinomialNB()
model2.fit(X_train2,y_train2)

MultinomialNB()

In [279]:
model2.score(X_test2, y_test2)

0.7210782478472483

In [291]:
seasonal_predicted=model2.predict_proba(X_test_seasonal)[:,1]

In [281]:
seas_label_predicted=model2.predict(X_test_seasonal)

In [293]:
seasonal_predicted

array([0.13806315, 0.08926887, 0.33078497, ..., 0.14109028, 0.53101002,
       0.35316535])

In [303]:
submission=pd.DataFrame({
    'respondent_id': test_csv['respondent_id'],
    'xyz_vaccine': xyz_predicted,
    'seasonal_vaccine': seasonal_predicted
})

In [304]:
submission.to_csv('submissiond.csv',sep='\t')